login_login_homepage:
    path:     /login
    defaults: { _controller: LoginLoginBundle:Default:index }
    
login_login_signup:
    path:    /signup
    defaults: { _controller: LoginLoginBundle:Default:signup } 

login_login_signup:
    path:    /status
    defaults: { _controller: LoginLoginBundle:Statusprogress:status }
    
login_login_home:
    path:   /home
    defaults: { _controller: LoginLoginBundle:Home:home }

login_login_main:
    path:  /main
    defaults: { _controller: LoginLoginBundle:Main:main }